### ISSUE TITLE
Patch file not creating 

### ISSUE THREAD

**Issue by harikesavan** [mahmoodlab/CLAM#28] opened 2021-01-16 14:35 UTC
I trird to run the create_patches.py file using the command from the readme.

**python create_patches.py --source dataset_lung --save_dir new --patch_size 256 --seg --patch --stitch**

but always getting an error

OSError: Unable to open file (unable to open file: name = 'new/patches/TC_W107_4.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by fedshyvana** [comment] 2021-01-16 15:34
Can you check under the new/masks/ folder for the mask corresponding TC_W107_4 and see whether the segmentation is correct?
It's likely caused by the default segmentation parameters you're using being ill-suited to your dataset, so you should try a different set of default parameters/define your own parameters, or adjust parameters for particular slide in the dataset. You can read the README in more details to understand how.

**Comment by fedshyvana** [comment] 2021-01-16 15:35
I am guessing basically the same question asked as [here](https://github.com/mahmoodlab/CLAM/issues/27)

**Comment by harikesavan** [comment] 2021-01-16 16:41
Thanks for the reply. There was no segmentation on those images.  And
played around with the parameter, still didn't work.

best regards a
hari

**Comment by fedshyvana** [comment] 2021-01-16 16:59
can you show me the segmentation image, and the corresponding parameters you used?

**Comment by harikesavan** [comment] 2021-01-16 17:02
Sure, here you go.

python create_patches.py --source dataset_lung --save_dir new --patch_size
256  --seg --patch --stitch --patch_level 5 --step_size 500 [image:
TC_W108_1.png]

**Comment by fedshyvana** [comment] 2021-01-16 17:08
maybe i was not clear, but i meant the segmentation parameters and not things like patch_size, patch_level, step_size, those do not affect segmentation. 

I mean things like a_h, a_t, and threshold parameters, which can be found either in the generated csv file, or in the template files in the preset folder. 

Also I cannot see the image you just posted, if you can post it I can maybe recommend what parameters to use.

**Comment by harikesavan** [comment] 2021-01-16 17:15
Ok, I will do that.

**Comment by fedshyvana** [comment] 2021-01-17 23:18
closing this for now. feel free to reopen if you experience more issues.

**Closed by fedshyvana** 2021-01-17 23:18 UTC

**Comment by harikesavan** [comment] 2021-01-24 00:16
Dear Mahmood,
thanks for the help. Lower the a_h in the present solved the problem. I
have set the a_h values to 0.1 to make it work. Do you think this will
affect the classification?

best regrads,
hari

**Comment by fedshyvana** [comment] 2021-01-24 00:19
It should not affect classification as long as you verify that you're getting the correct segmentation/patching. You can verify this easily by looking at the "masks" folder and "stitches" folder respectively

**Comment by harikesavan** [comment] 2021-01-24 18:36
Thank you for the clarification and prompt response.

The code run through, but still encountering some problems with the model.
could you please help me with this?
[image: image.png]

**Comment by fedshyvana** [comment] 2021-01-24 19:27
I cannot see the image you posted. Can you re-post it and make sure it's visible? 

Max

**Comment by harikesavan** [comment] 2021-01-24 19:29
Sure, here it is.

Traceback (most recent call last):
  File "/home/hari/project/CLAM/main.py", line 215, in <module>
    results = main(args)
  File "/home/hari/project/CLAM/main.py", line 49, in main
    results, test_auc, val_auc, test_acc, val_acc  = train(datasets, i,
args)
  File "/home/hari/project/CLAM/utils/core_utils.py", line 184, in train
    train_loop_clam(epoch, model, train_loader, optimizer, args.n_classes,
args.bag_weight, writer, loss_fn)
  File "/home/hari/project/CLAM/utils/core_utils.py", line 238, in
train_loop_clam
    logits, Y_prob, Y_hat, _, instance_dict = model(data, label=label,
instance_eval=True)
  File
"/home/hari/anaconda3/envs/clam/lib/python3.7/site-packages/torch/nn/modules/module.py",
line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hari/project/CLAM/models/model_clam.py", line 184, in forward
    instance_loss, preds, targets = self.inst_eval_out(A, h, classifier)
  File "/home/hari/project/CLAM/models/model_clam.py", line 153, in
inst_eval_out
    top_p_ids = torch.topk(A, self.k_sample)[1][-1]
RuntimeError: invalid argument 5: k not in range for dimension at
/opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THC/generic/THCTensorTopK.cu:23

Process finished with exit code 1

**Comment by fedshyvana** [comment] 2021-01-24 21:49
can i know the range of bag sizes in the dataset? it's the number of patches extracted per slide. (i.e. what's the minimum, maximum, median bag size in your dataset).

**Comment by fedshyvana** [comment] 2021-01-24 21:52
the issue appears to suggest that you have too few patches in some slides to perform the inst-level clustering task. You could ofc solve this issue by simply enabling --no_inst_cluster in training, but it seems a bit unreasonable for the number of patches to be so low. have you already verified the "masks" and "stitches" to make sure everything looks right?

**Comment by harikesavan** [comment] 2021-01-25 07:41
Yes, I did.

But the images in the stitches were not the not clean as the mask. The
images are not visible clearly. I have attached the link for the PNG images
of both mask and stitches. I hope it helps.

https://ibb.co/9WrMQCn
https://ibb.co/GHJJvZv
